import { Annotation } from '@langchain/langgraph';

// Shared state flowing through the three-agent graph.
export const AgentState = Annotation.Root({
  // The new transcription chunk under investigation (delta since last analysis).
  paragraph: Annotation<string>({ reducer: (a, b) => b ?? a, default: () => '' }),

  // Whether the summarizer node should run. When false, START flows directly
  // into the investigator and summary stays empty.
  enableSummary: Annotation<boolean>({ reducer: (a, b) => b ?? a, default: () => true }),

  // The stored rolling conversation summary from the previous analysis run.
  // Consumed by the summarizer node to produce the next summary.
  prevSummary: Annotation<string>({ reducer: (a, b) => b ?? a, default: () => '' }),

  // The freshly computed rolling conversation summary, injected into the
  // investigator, validator, and resolver prompts as shared context.
  summary: Annotation<string>({ reducer: (a, b) => b ?? a, default: () => '' }),

  // Human-readable label for the source of `paragraph` (e.g. "speaker").
  sourceLabel: Annotation<string>({ reducer: (a, b) => b ?? a, default: () => '' }),

  // Transcription from the other source (e.g. the host's microphone) so the
  // agents can avoid re-asking what has already been said.
  context: Annotation<string>({ reducer: (a, b) => b ?? a, default: () => '' }),

  // Human-readable label for the source of `context` (e.g. "microphone").
  contextLabel: Annotation<string>({ reducer: (a, b) => b ?? a, default: () => '' }),

  // Questions generated by the investigator agent.
  questions: Annotation<string[]>({ reducer: (a, b) => b ?? a, default: () => [] }),

  // Questions that survived the validator agent.
  validatedQuestions: Annotation<string[]>({
    reducer: (a, b) => b ?? a,
    default: () => [],
  }),

  // Currently-open questions (id + text) fed to the resolver.
  openQuestions: Annotation<{ id: number; question: string }[]>({
    reducer: (a, b) => b ?? a,
    default: () => [],
  }),

  // Open questions resolved by the resolver, each with a minimal reason.
  answered: Annotation<{ id: number; reason: string }[]>({
    reducer: (a, b) => b ?? a,
    default: () => [],
  }),
  stale: Annotation<{ id: number; reason: string }[]>({
    reducer: (a, b) => b ?? a,
    default: () => [],
  }),
});
