import { Annotation } from '@langchain/langgraph';

// Shared state flowing through the three-agent graph.
export const AgentState = Annotation.Root({
  // The new transcription chunk under investigation (delta since last analysis).
  paragraph: Annotation<string>({ reducer: (a, b) => b ?? a, default: () => '' }),

  // Human-readable label for the source of `paragraph` (e.g. "speaker").
  sourceLabel: Annotation<string>({ reducer: (a, b) => b ?? a, default: () => '' }),

  // Transcription from the other source (e.g. the host's microphone) so the
  // agents can avoid re-asking what has already been said.
  context: Annotation<string>({ reducer: (a, b) => b ?? a, default: () => '' }),

  // Human-readable label for the source of `context` (e.g. "microphone").
  contextLabel: Annotation<string>({ reducer: (a, b) => b ?? a, default: () => '' }),

  // Questions generated by the investigator agent.
  questions: Annotation<string[]>({ reducer: (a, b) => b ?? a, default: () => [] }),

  // Questions that survived the validator agent.
  validatedQuestions: Annotation<string[]>({
    reducer: (a, b) => b ?? a,
    default: () => [],
  }),

  // Currently-open questions (id + text) fed to the resolver.
  openQuestions: Annotation<{ id: number; question: string }[]>({
    reducer: (a, b) => b ?? a,
    default: () => [],
  }),

  // Open question ids resolved by the resolver.
  answeredIds: Annotation<number[]>({ reducer: (a, b) => b ?? a, default: () => [] }),
  staleIds: Annotation<number[]>({ reducer: (a, b) => b ?? a, default: () => [] }),
});
